language: java
jdk: openjdk12

deploy:
  provider: heroku
  api_key:
    secure: fv+gBn4LLqwxpl6p2KdSgMXK0mYVlEB15ss4GHtYXCwS9oSgtdwjqlW/m8Qj0GhQxjXu9HZyFnb5P9wXpD1dVBhUhsDcRyxoBjStp5+Rywz7gJ9M42+EczS9X4wI+zjGZL+PoU0zXeob/+8UK/S1MOCZczvHZDri6we/s28kln/S8nk3D8ijTDTqSGFbD1kTbBOAhZ52NQ5U4SaSPcDx7nVPPrIDKEuoHR0UQc6NPJi3ZzdOTz01QVJ79UMs89B0Tspyph4s/eVk1TCK2K3GuYRDX3237yNhEK2Or1DoKuQyzG0k7WWHQlV0FWbTWYRNsKeeNefqhMn6ZMc1kRkaDTDlEzVUgLdgIJV8BMAJY4DBHLplQh+eZ8Ksg0Fvzvrinmzhgo9EWVc5sLe7B8bYubQRMbzMx7zjECT37M2ALplZzFmJTQU/HyjoPgw33OeVKI+JSWaWTOL3hEoTdLo4lt2vosTi5zl+HkW+oBQSSyjysNxbcp10AGFY3o+rKerFYjBc4Yle6QVxKasOGI40vqwpMW2lCegJBAatheyc2ues7RWK+MdrYA541YKwgAOrGvK4AHq8jcFQX+Me/NsYbGEThXEOiD8G/NVuj779LGTUcysQPxwAMqJ9e4NU7nO93+WyEDGiYWcuvA1N/8XViWUEzJcScKjIvquLkuV5FV0=
  app: leafalone
