language: java
jdk: openjdk12
deploy:
  provider: heroku
  api_key:
    secure: cb3OhmjU4wWBaQxbitKpnHvkaaPfyDMD0L3vAPitfsQjNUcw2EtsmRJsx0h8lxF86n6rwz+uhNMcyOFw8ev4SdDuYPxPUHDy2ukQLlILPPWzW2KrKNba8KcQAHdZQjD0/NK42kRbGKUW89OuNsq7rLyHdEFmT9uDUIAGse3YAUWSEVZHBzyXkSNql/HCBxUl4B7mRQtYFWQ/sZXZFfpb10ahjMZXv3nOjby4ZC8L/02GZcMghR3CbmRTU/2aWWupbkOOdgSgPFEASKRWEWG8gLNWHJygqvJHnXA1xwu672DK00YY8r6xgv1oMRxk/MPi0Gw2ywutJeU6FzNwO+BqPFcLmdfBIm39wWOJDPMdTkSHS4YurAd3FvFNE6tXp41qPt0d/IFZvaSZpv9EhORFrxpkHFo7lpG6ihThYspEXD2eIPnU1KWqM6tcFgr5RAZ5iSePMlYZJzvTjoFBhyc/IDmIHvsD+iM19/g2iZU5JJprwTvkHW5W3tdz+z+Hmpbm1SXvb2ppQ08Q5t22vm4Yu1UgBa4JmBMqu2AwRH3fnbXZk7lKYyHtVHay+QhlJT+Cjhf6LnVgdxrsNbCVk5tSQSFe7BCaa0vgSu6eh/F9531iM8uTnRYzAzXfmnPqJ0n7wPuRRnePB8SjL9d1qZ/KstQynC37IhMcUlbmTEOCyCg=
  app: leafalone
  on:
    repo: JanUrbanHtw/LeafAlone
